name: survivors_game
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: 1.22.0 # 안정화된 버전으로 진행
  flame_audio: ^2.0.4  # 사운드 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  # 이미지 
  - assets/images/player.jpg
  - assets/images/heart.png
  - assets/images/hit.png
  - assets/images/enemy.png
  - assets/images/background.jpg

  # 사운드
  - assets/audio/hit.mp3